<?php

/*  Extract RDF content from CSV file using URIs that are generated by
    autoincrement.  

    Adapted source of csvToArray from 
    http://stackoverflow.com/questions/17761172/php-csv-string-to-array 

*/

function TurtleEnvelope() {
  return '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix geosparql: <http://www.opengis.net/ont/geosparql#> .
@prefix jso: <http://jedeschule.de/ontology/ns#> .

<http://jedeschule.de/HGG-Datenextrakt/> a owl:Ontology ;
   rdfs:label "RDF als CSV-Extrakt für Sachsen" ;
   rdfs:comment "Extrakt aus der csv-Quelle sachsen.csv mit dem Skript csv2rdf.php" .

';
}

function getSchoolTypes($a) {
    $a1=$a['school_type'];
    $b=array();
    $b[]=createURI('schooltype',$a1).' a jso:SchoolType';
    $b=addEntry($b,"rdfs:label",$a1) ; 
    return join(";\n  ",$b) . " . \n\n"; 
}

function getEntry($a) {
    $b=array();
    $id=$a['id'];
    $b[]='<http://jedeschule.de/'.$id.'> a jso:Bildungseinrichtung';
    $b=addEntry($b,"jso:id",$a['id']) ; 
    $b=addEntry($b,"rdfs:label",$a['name']) ; 
    $address=array();
    $address=preg_split("/\s*(\d{5})\s*/",$a['address'],-1,PREG_SPLIT_DELIM_CAPTURE);
    $b=addEntry($b,"jso:strasse",trim($address[0])) ; 
    $b=addEntry($b,"jso:plz",trim($address[1])) ; 
    $b=addEntry($b,"jso:ort",trim($address[2])) ; 
    $b=addEntry($b,"jso:address",$a['address']) ; 
    $b=addLink($b,"a",'schooltype',$a['school_type']) ; 
    $b[]= ' geosparql:asWKT "Point('.$a['lat'].' '.$a['lon'].')"' ;
    //$b=addEntry($b,"jso:lat",$a['lat']) ;  
    //$b=addEntry($b,"jso:lon",$a['lon']) ; 
    $b=addEntry($b,"jso:phone",$a['phone']) ; 
    $b=addEntry($b,"jso:fax",$a['fax']) ; 
    $b=addEntry($b,"jso:full_time_school",$a['full_time_school']) ;
    return join(";\n  ",$b) . " . \n\n"; 
}
function activities($a) {
    global $cnt; $cnt++;
    $b=array();
    $b[]='<http://jedeschule.de/activity/'.$cnt.'> a jso:Activity';
    $b[]=' jso:hasId <http://jedeschule.de/'.$a['id'].'> ';
    $b=addEntry($b,"jso:ag_name",$a['ag_name']) ;
    $b=addLink($b,"jso:ag_cat","ag_cat",$a['ag_cat']) ;
    return join(";\n  ",$b) . " . \n\n"; 
}

function addEntry($b,$key,$value) {
    $value=str_replace('"','\"',trim($value));
    if (empty($value)) { return $b; }
    $b[]=" $key \"$value\"" ;
    return $b;
}

function addLink($b,$key,$prefix,$value) {
    $uri=trim($value);
    if (empty($value)) { return $b; }
    $uri=createURI($prefix,$uri);
    $b[]=" $key $uri" ;
    return $b;
}

function createURI($prefix,$name) { 
    $name=strtolower(trim(preg_replace('/\s\s+/', '', $name)));
    $name=str_replace(
        array('ß',  'ä',  'ü',  'ö'),
        array('ss', 'ae', 'ue', 'oe'),
        $name);
    $name=preg_replace('/\W/', '', $name);
    return "<http://jedeschule.de/$prefix/$name>";
}

function csvToArray($file) {
    $rows = array();
    $headers = array();
    if (file_exists($file) && is_readable($file)) {
        $handle = fopen($file, 'r');
        while (!feof($handle)) {
            $row = fgetcsv($handle, 10240, ',', '"');
            $row = str_replace(' ',' ',$row);
            if (empty($headers))
                $headers = $row;
            else if (is_array($row)) {
                array_splice($row, count($headers));
                $rows[] = array_combine($headers, $row);
            }
        }
        fclose($handle);
    } else {
        throw new Exception($file . ' doesn\'t exist or is not readable.');
    }
    return $rows;
}

// ======= main ===========

$a=csvToArray("../schools/sachsen.csv");
//$out=join("\n",array_map("getSchoolTypes",$a));
$out=join("\n",array_map("getEntry",$a));

/*

$a=csvToArray("../activities/activity-schools-SN.csv");
$cnt=10000;
$out.=join("\n",array_map("activities",$a));
*/

echo TurtleEnvelope().$out;
